### PR TITLE
Added AUR package

### PR DESCRIPTION
**Pull request by q60**
i'll maintain it

### CODE REVIEW

**Comment by KikyTokamuro** [comment]
This is a great idea;)

But first, correct this comment https://aur.archlinux.org/packages/fetch-scm#comment-822664 and then I'll accept the pull request.

**Comment by q60** [comment]
> This is a great idea;)
> 
> But first, correct this comment https://aur.archlinux.org/packages/fetch-scm#comment-822664 and then I'll accept the pull request.

I will correct only the second issue, because there's no need in installing license, if it's provided by the corresponding variable. It is unnecessary step at all, as I read AUR guidelines. But he's right about `provides`, which will be fixed as soon as I get to my PC. besides, removing `provides` doesn't change a thing at all, it's all about PKGBUILD code quality.

**Comment by KikyTokamuro** [comment]
@q60 As far as I understand, you have fulfilled the AUR requirements?

**Comment by q60** [comment]
i did

**Pull request merged**
